Update control-panel.md
WordPress/Advanced-administration-handbook pull request #202
Opened 2023-04-20 23:34 UTC by sbillik

Hello! I'm a technical writer on the Documentation team at cPanel.

The existing file contains outdated installation instructions for cPanel, as we now prefer the use of WP Toolkit to install WordPress. I've therefore updated the document accordingly and have also combined the relevant information for WP Toolkit for cPanel and Plesk since both control panels use it. My updates have passed review by both a cPanel developer and another technical writer on the cPanel Documentation team.

Note that we would also like to get the page at https://wordpress.org/documentation/article/using-cpanel/ updated accordingly. Thanks in advance for your consideration of these changes!

2023-04-24 10:03 UTC, Crixu commented
Thanks for the work @sbillik. The whole document should be around multiple control panels in the best case and I see that you changed the structure of the document itself. I'll add more details into the inline review

2023-04-24 10:08 UTC, Crixu requested changes

2023-04-24 10:08 UTC, Crixu commented on server/control-panel.md
> +This document describes how to install WordPress® in the cPanel & WHM and Plesk control panels using WP Toolkit.
This document should be generic for multiple control panels and this sentence should be under the cPanel and Plesk headlines

2023-04-24 10:08 UTC, Crixu commented on server/control-panel.md
> +## WP Toolkit
Please change back to cPanel or "cPanel WP Toolkit". if you want to cover both Plesk and cPanel, use only one headline like "WP Toolkit for cPanel and Plesk"

2023-04-24 10:08 UTC, Crixu commented on server/control-panel.md
> +cPanel & WHM versions 102 and above install WP Toolkit by default. It is available in Plesk if the server administrator has installed the WP Toolkit extension. The WP Toolkit extension is free with t
please remove any advertising sentences for the panels. If the tool is not available for free it shouldn't be covered in the documentation here.

2023-04-24 10:08 UTC, Crixu commented on server/control-panel.md
> +To install WordPress, WP Toolkit retrieves data from wordpress.org. By default, if WP Toolkit cannot establish an initial connection in 15 seconds, it considers wordpress.org unavailable.
Please include this in your documentation not here.

2023-04-25 23:23 UTC, sbillik commented
Thanks for your feedback, @Crixu! I've made the changes you requested. I hope the document now meets WordPress standards!

2023-04-26 06:21 UTC, Crixu approved these changes

2023-04-26 12:34 UTC, merged